# Generated by Django 6.0.5 on 2026-05-31 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('events', '0001_initial'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='invitations.invitation', verbose_name='invitación'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['qr_code'], name='idx_attendance_qr'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['event'], name='idx_attendance_event'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['checkin_time'], name='idx_attendance_checkin'),
        ),
    ]
