# Generated by Django 6.0.5 on 2026-06-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='qr_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='hash QR'),
        ),
    ]
