# Generated by Django 6.0.5 on 2026-05-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('event_date', models.DateField(verbose_name='fecha del evento')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='hora del evento')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='ubicación')),
                ('category', models.CharField(choices=[('conference', 'Conferencia'), ('workshop', 'Taller'), ('seminar', 'Seminario'), ('networking', 'Networking'), ('social', 'Social'), ('corporate', 'Corporativo'), ('other', 'Otro')], default='other', max_length=100, verbose_name='categoría')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='imagen')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('finished', 'Finalizado')], default='draft', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-event_date', 'event_time'],
            },
        ),
    ]
