# Generated by Django 6.0.5 on 2026-05-31 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='organizador'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='idx_event_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='idx_event_status'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='idx_event_category'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='idx_event_organizer'),
        ),
    ]
